apiVersion: apps/v1
kind: StatefulSet 
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/hello:5.0
        name: hello
