apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      ports:
      - containerPort: 8080
      containers:
      - name: flask-app
        image: image-registry.openshift-image-registry.svc:5000/openshift/flask-app:latest
        imagePullPolicy: IfNotPresent

        env:
        - name: MYSQL_HOST 
          value: mysql

        - name: MYSQL_USER 
          valueFrom:
            secretKeyRef:
              name: mysql-secret 
              key: MYSQL_PASSWORD 

        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE 
