apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-jegan  #Replace 'jegan' with your name
      containers:
      - name: mysql
        image: image-registry.openshift-image-registry.svc:5000/openshift/mariadb:1.0
        imagePullPolicy: IfNotPresent

        volumeMounts:
        - name: mysql-storage
          mountPath: /bitnami/mariadb/data

        env:
        - name: MARIADB_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret 
              key: MYSQL_ROOT_USER 
        - name: MARIADB_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysql-secret 
              key: MYSQL_ROOT_PASSWORD 
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret 
              key: MYSQL_USER 
        - name: MARIADB_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysql-secret 
              key: MYSQL_PASSWORD 

        - name: MARIADB_DATABASE
          valueFrom: 
             secretKeyRef:
               name: mysql-secret 
               key: MYSQL_DATABASE 
